version: "3"
services:
  Burrito_frontend:
    build: ./Burrito_frontend
    ports:
      - "3000:80"
    depends_on:
      - Burrito_backend
    restart: unless-stopped

  Burrito_backend:
    build: ./Burrito_backend
    expose:
      - "3001"
    environment:
      - PORT=3001
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=anviam
      - DB_DIALECT=mysql
      - DB_NAME_DEVELOPMENT=BurritoShop
      - JWTKEY=khfjgjhgjhgej834737852529y1tu3ihqjebhf3brghebg
      - NODE_ENV=DEVELOPMENT
    depends_on:
      - mysqldb
    restart: unless-stopped

  mysqldb:
    image: "mysql:8"
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=anviam
      - MYSQL_DATABASE=BurritoShop
      - MYSQL_USER=root
      - MYSQL_PASSWORD=anviam
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql